# Generated by Django 4.0.3 on 2022-04-03 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_categories_slug_recipes_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='ingredients',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='recipes',
            old_name='name',
            new_name='title',
        ),
    ]
